---
  local:
    host: "localhost"
    externalPort: 8000
    internalPort: 8001
  components:
    gremlinServer:
      name: "Gremlin Server"
      dir: "gremlin_server"
      config: "conf/gremlin-server-trueno.yaml"
      cmdUnix: "bin/gremlin-server.sh"
      interpreter: "bash"
      deploy: true
      cmdFlags:
        - 'conf/gremlin-server-trueno.yaml'
      configFlags:
        host: "localhost"
        port: 8002
      hostMappings:
        -
          - 'configFlags'
          - 'host'
      readyString: "Channel started at port"
      next: []
    elasticsearch:
      name: "Elasticsearch"
      dir: "elasticsearch"
      config: "config/elasticsearch.yml"
      cmdUnix: "bin/elasticsearch"
      interpreter: "bash"
      deploy: true
      configFlags:
        cluster.name: "trueno"
        node.name: ${HOSTNAME}
        http.port: 8004
        network.host: 0.0.0.0
        transport.tcp.port: 9300
        transport.host: localhost
        action.auto_create_index: false
        discovery.zen.ping.unicast.hosts: ["localhost"]
        path.data: "elasticsearch"
        indices.requests.cache.size: "35%"
        indices.queries.cache.size: "30%"
        bootstrap.system_call_filter: false
      hostMappings:
        -
          - 'configFlags'
          - 'network.host'
        -
          - 'configFlags'
          - 'discovery.zen.ping.unicast.hosts'
          - 0
      clusterMappings:
        -
          - 'configFlags'
          - 'discovery.zen.ping.unicast.hosts'
      readyString: "] started"
      next: ["truenoElasticBridgeServer"]
    sparkMaster:
      name: "Spark Master"
      dir: "spark"
      cmdUnix: "bin/spark-class"
      interpreter: "bash"
      deploy: true
      suppressErrors: true
      cmdFlags:
        - "org.apache.spark.deploy.master.Master"
        - "-h"
        - "localhost"
        - "-p"
        - 8005
        - "--webui-port"
        - 8006
      hostMappings:
        -
          - 'cmdFlags'
          - 2
      readyString: "Started REST server for submitting applications on port"
      next: []
      #next: ['truenoComputeServer']
    sparkWorker:
      name: "Spark Worker"
      dir: "spark"
      cmdUnix: "bin/spark-class"
      interpreter: "bash"
      deploy: true
      suppressErrors: true
      joinCmdFlags: ""
      cmdFlags:
        - "org.apache.spark.deploy.worker.Worker "
        - "spark://"
        - "localhost"
        - ":"
        - 8005
        - " -d "
        - "spark"
      hostMappings:
        -
          - 'cmdFlags'
          - 2
      readyString: "Successfully registered with master"
      next: []
    truenoComputeServer:
      name: "Trueno Compute Server"
      dir: "trueno_compute_server"
      cmdUnix: "server_start.sh"
      interpreter: "bash"
      deploy: false
      cmdFlags:
         -
      readyString: "Bound to"
      next: []
    ui:
      name: "Trueno UI"
      deploy: false
      host: "localhost"
      ports:
        pm2Gui: 8088
        elasticSearch: 8004
      hostMappings:
        -
          - 'host'
      next: []
    truenoElasticBridgeServer:
      name: "Trueno ElasticSearch Bridge Server"
      dir: "trueno_elastic_bridge_server"
      cmdUnix: "bridgeServer.sh"
      interpreter: "bash"
      deploy: false
      numberOfShards: 2
      replicaPercent: 0.8
      cmdFlags:
         - "localhost"
         - 8007
         - 2
         - 1
      hostMappings:
        -
          - 'cmdFlags'
          - 0
      readyString: "Trueno Bridge server is up"
      next: []
    cerebro:
      name: "Cerebro"
      dir: "cerebro"
      cmdUnix: "bin/cerebro"
      interpreter: "bash"
      deploy: true
      joinCmdFlags: ""
      cmdFlags:
        - "-Dhttp.port="
        - 8008
        - " "
        - "-Dhttp.address="
        - "0.0.0.0"
        - " "
        - "-Dhosts.0.host="
        - "http://"
        - "localhost"
        - ":"
        - 8004
      hostMappings:
        -
          - 'cmdFlags'
          - 8
      readyString: "Listening for HTTP on"
      next: []